name: CI/CD — Production Deploy

on:
  push:
    branches:
      - main

jobs:
  pull:
    name: Git pull
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /var/www/html/annuaire
            git pull origin main

  deploy:
    name: Deploy ${{ matrix.site }}
    needs: pull
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [maximefreelance]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /var/www/html/annuaire
            make reload-prod SITE=${{ matrix.site }}
            make migrate-prod SITE=${{ matrix.site }}
